#!/bin/bash -e

#this is a comment

quiet_mode=0
server_list=$@

if [ "$1" == "-q" ]; then
        quiet_mode=1
        server_list="${@:2}"
fi


if [ $quiet_mode == 0 ]; then
    echo ===============================
    echo == multi-ping test tool v1.0 ==
    echo ===============================
fi

for server in $server_list; do
        if [ $quiet_mode == 1 ]; then
        fping $server 2>/dev/null
        else
            fping $server
    fi
done

if [ $quiet_mode == 0 ]; then
    echo Done!
fi
